
##################################################
### LOGIN
##################################################

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@meritix.com",
  "password": "Password123"
}

###

@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiYWRtaW5AbWVyaXRpeC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3ODUzNTQ5MDQsImV4cCI6MTc4NTQ0MTMwNH0.bqsVHyPH6GntZImQXk5nXoolNzoxpf4FYY6LgXckTI0
##################################################
### Dashboard Summary
##################################################

GET {{baseUrl}}/dashboard/summary
Authorization: Bearer {{token}}

###

##################################################
### Recent Schools
##################################################

GET {{baseUrl}}/dashboard/recent-schools
Authorization: Bearer {{token}}

###

##################################################
### Recent Classes
##################################################

GET {{baseUrl}}/dashboard/recent-classes
Authorization: Bearer {{token}}

###

##################################################
### Recent Sections
##################################################

GET {{baseUrl}}/dashboard/recent-sections
Authorization: Bearer {{token}}